name: PR Build

on:
  pull_request:

concurrency:
  group: pr-build-${{github.event.pull_request.number}}
  cancel-in-progress: true

jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --watch=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ./dist/
            ./netlify.toml
