name: PR Preview

on:
  workflow_run:
    workflows: [PR Build]
    types:
      - completed

jobs:
  pr-preview:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-workflow_run-status@v1

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: artifact
          workflow: ${{github.event.workflow_run.workflow_id}}
          run_id: ${{github.event.workflow_run.id}}

      - name: Get PR Event
        id: get_pr_event
        uses: potiuk/get-workflow-origin@v1_3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          sourceRunId: ${{github.event.workflow_run.id}}

      - name: Deploy Preview
        timeout-minutes: 5
        env:
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
        run: npx netlify-cli deploy --alias ${{steps.get_pr_event.outputs.pullRequestNumber}}
